### PR TITLE
[ UP-3035 ] Fix password field processing

### LINKED ISSUE #64: Error when using uptime_check_http with username/password
Providing a password always results in a failure in `terraform apply`: `.password: inconsistent values for sensitive attribute.`.

## How to reproduce

Given the 3 files below:

`versions.tf`:

```
terraform {
  required_version = "~> 1.5.7"

  required_providers {
    uptime = {
      source  = "uptime-com/uptime"
      version = "2.4.1"
    }
  }
}

provider "uptime" {
  token = var.uptime_token
}
```

`variables.tf`:

```
variable "uptime_token" {
  type        = string
  description = "The Uptime.com API token"
}

variable "chartmuseum_password" {
  type        = string
  description = "The password for the chartmuseum user"
  sensitive   = true
}
```

`main.tf`:

```
resource "uptime_check_http" "chartmuseum" {
  name    = "chartmuseum"
  address = "<REDACTED>"

  is_paused = true

  username = "<REDACTED>"
  password = var.chartmuseum_password
}
```

## `terraform apply`

```
[...]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to uptime_check_http.chartmuseum, provider "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an unexpected new value: .password: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### PR DESCRIPTION
**Pull request by gigovich**
Provide persistent value for password field, to satisfy Terraform resource flow. Fix #64 github issue.

### CODE REVIEW

File: internal/provider/resource_check_http.go [hunk 1]
```diff
@@ -244,15 +244,27 @@ type CheckHTTPResourceAPI struct {
 }
 
 func (a CheckHTTPResourceAPI) Create(ctx context.Context, arg upapi.CheckHTTP) (*upapi.Check, error) {
-	return a.provider.api.Checks().CreateHTTP(ctx, arg)
+	resp, err := a.provider.api.Checks().CreateHTTP(ctx, arg)
+	if err == nil {
```
Comment (mikluko) [inline internal/provider/resource_check_http.go:248]: I would expect a circuit breaker here, like:

```
if err != nil {
    return resp, err // ...or nil, err if applicable
}
resp.Password = arg.Password
return resp, err
```

Abort early if error, do processing otherwise.

**Review by mikluko — CHANGES_REQUESTED** [review]

File: internal/provider/resource_check_http.go (hunk 1 above)
Comment (gigovich) [reply internal/provider/resource_check_http.go]: I can't agree with that in this particular case, but it is not a big deal. Fixed.

**Review by mikluko — APPROVED** [review]
